name: Deploy to GEA Botswana Shared Drive

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Google Apps Script
        uses: daichan4649/google-apps-script-deploy-action@v1
        with:
          # This is your JSON key stored in GitHub Secrets
          credentials: ${{ secrets.GAS_SERVICE_ACCOUNT_KEY }}
          
          # The Script ID of your project on the Shared Drive
          script-id: "1mkzpnNfUm-ZTW-G6wEdGg4Jt1KiChOXrV5qjBNkm3eqx43Yn-7Z-2Ffv"
          
          # Your admin address to bypass the 16-hour limit
          impersonate-email: "treasurer@geabotswana.org"
